app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Auth::loginUsingId(8);

use App\User;

Route::get('/test', function(){

});

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::model('players', 'App\User');
Route::model('castles', 'App\Castle');
Route::model('buildings', 'App\Building');
Route::model('units', 'App\UnitType');
Route::model('generals', 'App\General');
Route::model('battles', 'App\Battle');

Route::resource('generals.battles', 'BattlesController');
Route::resource('players', 'UserDashboardController');
Route::resource('players.castles', 'CastlesController');
Route::resource('players.buildings', 'UserBuildingsController');
Route::resource('castles.buildings', 'CastleBuildingsController');
Route::resource('castles.units', 'CastleUnitsController');

Route::get('/dashboard/{user}', 'UserDashboardController@index');

Route::get('/castle/{id}', 'UserCastleController@index');



Route::group(['middleware' => ['ownerOrAdmin']], function () {
    //
});

resources/views/partials/army.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="container">
        <h3>{{$castle->name}} Armies</h3>
        <hr>
        @foreach($castle->generals as $general)

            {{$general->name}} Army
            <hr>

            {{ Form::model($general, array('route' => array('generals.battles.create', $general->id), 'method' => 'GET')) }}
            {{ csrf_field() }}
                {!! Form::submit('GO to WAR!', ['class' => 'btn btn-primary', ]) !!}
            {!! Form::close() !!}

            <hr>

                <table id="js-groups" class="table table-striped" style="border-top: 1px solid #eee;">
                    <thead>
                        <tr>
                            <th>Unit Type</th>
                            <th>Count/Numbers</th>
                            <th>Requirements</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($unit_types as $type)
                        <tr>
                            <td>{{$type->type}}</td>
                            <td>{{ $general->countUnitsByTypeId($type->id) }}</td>
                            <td>
                                @foreach($buildings as $building)
                                    {{ $building->type }} level required {{ $type->getLevelRequiredByBuildingId($building->id) }}
                                @endForeach
                            </td>
                            {{--@if($general->on_mission == true)--}}
                                <td>
                                    {!! Form::model($castle, ['route' => ['castles.units.store', $castle->id, $type]]) !!}
                                    {!! Form::hidden('type', $type->id ) !!}
                                    {!! Form::hidden('general', $general->id ) !!}
                                        {{ csrf_field() }}

                                        {!! Form::submit('Create', ['class' => 'btn btn-primary']) !!}
                                    {!! Form::close() !!}
                                </td>
                            {{--@endif--}}
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <hr>

        @endforeach

@endsection

resources/views/partials/castle.blade.php
@extends('layouts.dashboard')

@section('content')


    <div class="container">
        <h3>{{$castle->name}}  Info</h3>

            {!! link_to_route('castles.units.index', 'Inspect The Army', array($castle->id), array('class' => 'btn btn-info')) !!}
        <hr>

        <div class="row">
            <div class="col-md-3">
                <h2>Resources</h2>
                   <ol class="list-group">
                       @foreach($castle->resources()->get() as $resource)
                           @if($resource->type != 'Time')
                               <li>{{$resource->type}}  : {{ $resource->pivot->amount }} </li>
                           @endif

                       @endforeach
                   </ol>
            </div>
            <div class="col-md-3">
                <h2>Buildings</h2>
                <ol class="list-group">

                    @foreach($buildings as $building)
                        <li>{{$building->type}}  on Level  : {{ $building->pivot->level }} </li>
                    @endforeach
                </ol>
            </div>
            <div class="col-md-3">
                <h2>Armies</h2>
                @foreach($generals as $general)
                    Army of "{{$general->name}}"
                        <ol class="list-group">

                            @foreach($unit_types as $type)
                                <li>{{$type->type}}   : {{ $general->countUnitsByTypeId($type->id)}} </li>
                            @endforeach
                        </ol>
                @endforeach
            </div>
        </div>

    <div class="form-group">
        <table id="js-groups" class="table table-striped" style="border-top: 1px solid #eee;">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Level</th>
                    <th>Income</th>
                    <th>TimeToUpgrade</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach($buildings as $building)
                    <tr>
                        <td width="10%">{{ $building->type }}</td>
                        <td>{{ $building->pivot->level }}</td>
                        <td>Income</td>
                        <td>Time to Upgrade</td>
                        <td>
                            {!! Form::open(['url' => 'castles/'. $castle->id . '/buildings/' . $building->id , 'method' => 'PUT']) !!}
                                {!! Form::submit('Upgrade', ['class' => 'btn btn-primary']) !!}
                            {!! Form::close() !!}

                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    </div>
@endsection

resources/views/partials/navbar.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ url('/') }}">
                UglyByDesign
            </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            <ul class="nav navbar-nav">
                <li><a href="{{ url('/dashboard/'  . Auth::user()->id) }}">Dashboard</a></li>
                <li><a href="{{ url('/messages') }}">Messages</a></li>
                <li><a href="{{ url('/legend') }}">GameLegend</a></li>
                <li><a href="{{ url('/#') }}">Reports</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Castles <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        @foreach($castles as $castle)
                            <li><a href="/players/{{Auth::user()->id}}/castles/{{$castle->id}}">{{$castle->name}}</a></li>
                        @endforeach

                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Generals <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        @foreach($generals as $general)
                            <li><a href="#">{{$general->name}}</a></li>
                        @endforeach
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>